### PR TITLE
The new generation UI - Basic set up

### PR DESCRIPTION
**Pull request by taoalpha**
for https://github.com/polymorpher/one-wallet/issues/260

visit `/v2ui` to toggle on / off the new ui

### CODE REVIEW

**Comment by polymorpher** [comment]
We can have multiple PRs on this, each replacing some components while still making the UI usable. I think the network selector is missing in the changes so far

**Comment by taoalpha** [comment]
> We can have multiple PRs on this, each replacing some components while still making the UI usable. I think the network selector is missing in the changes so far

ya totally, the network selector is missing in the figma as well. I have my other changes on top of this and making separate PRs for them

**Review by polymorpher — APPROVED** [review]

**Comment by polymorpher** [comment]
Looks good, except the header needs some alignment and height regulation

image

image

**Comment by taoalpha** [comment]
> Looks good, except the header needs some alignment and height regulation
> 
> image
> 
> image

ya i think we will need a responsive design for this, especially now there are a lot more elements on the top

**Comment by taoalpha** [comment]
> Looks good, except the header needs some alignment and height regulation
> 
> image
> 
> image

added a new breakpoint at 1200 to hide the statsinfo, that will give us enough room to show the remaining items before reaching the mobile endpoint

**Comment by polymorpher** [comment]
headers are not working on mobile

**Comment by polymorpher** [comment]
fixed it

**Pull request merged**
