### PR TITLE
State refactor #3

### PR DESCRIPTION
**Pull request by taoalpha**
https://github.com/polymorpher/one-wallet/issues/198

### CODE REVIEW

**Comment by polymorpher** [comment]
change base branch?

**Comment by polymorpher** [comment]
Looks good, but it is not backward compatible. Users would see their wallets disappear and panic. Auto-migration is needed

**Comment by taoalpha** [comment]
> Looks good, but it is not backward compatible. Users would see their wallets disappear and panic. Auto-migration is needed

DONE

**Comment by polymorpher** [comment]
On a second thought, let's merge this first, since there will be a lot more changes later

**Comment by polymorpher** [comment]
The left-over variables in `wallet` are selected and assumed as wallets when `useSelector(state => state.wallet)` are used. Some pages fail to render because of this, for example, `List.jsx`

**Comment by polymorpher** [comment]
Fixed. Seems fine now.

**Pull request merged**
