### PR TITLE
reduce the bundle size

### PR DESCRIPTION
**Pull request by taoalpha**
modular lodash and antd + ant-design to reduce the bundle size

ideally this should be done by babel-plugin-import (partially), but it seems not work well with react 17, so update manually instead

https://github.com/polymorpher/one-wallet/issues/119

### CODE REVIEW

**Comment by taoalpha** [comment]
have to change the call signature for some of the methods due to the difference between the main and lp: https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity

**Comment by polymorpher** [comment]
It's good but impact seems to be very small. Let's focus on high impact stuff first

**Comment by taoalpha** [comment]
> It's good but impact seems to be very small. Let's focus on high impact stuff first

ya just some low hanging fruit

**Comment by taoalpha** [comment]
also from the bundle size, the ant + highlight account for 30-40% of the total size, the truffle itself seems pretty slim 

image

**Comment by polymorpher** [comment]
This can be almost entirely removed by taking out Truffle, in addition to itself

image
image

image

ENS related stuff seems to be taking an unreasonable amount of space (idna map, @ensdomain, unorm, etc.). We should take them out too and use custom implementation.

Similarly, perhaps we don't need html2canvas (could use html-to-image), react-player (just use HTML5 video), moment, and text-encoding.

Not sure why app.less takes so much space, is the image size not proportional to actual size?

**Comment by taoalpha** [comment]
ya I am looking into the truffle stuff, meanwhile, simply just by replacing all antd with antd/es can benefit us ~1Mb more, down to 
```
Assets: 
  main.js (9.05 MiB)
  ONEWalletWorker.js (675 KiB)
```

I think the app.less is also bloated by the antd styles...

image

**Comment by taoalpha** [comment]
after modular ant-design/icons:

```
Entrypoints:
  main (8.57 MiB)
      main.js
  ONEWalletWorker (675 KiB)
      ONEWalletWorker.js
```

**Pull request merged**
