### PR TITLE
fix: fallback to wallet on lost oldInfos

### PR DESCRIPTION
**Pull request by SystemDisc**
@polymorpher This should do it! Where do I see the bounty?

### CODE REVIEW

**Comment by polymorpher** [comment]
Thanks, but why should it fallback to wallet itself in this case? It must have found an identification key in this case that does not match root and matches with old cores (and their roots) in this case

**Comment by SystemDisc** [comment]
@polymorpher Yes, perhaps. Maybe I can share my screen with you and show you the issue I'm encountering. I think that may help us get to the crux of the problem.

**Comment by polymorpher** [comment]
Yes, thanks, that would be helpful. You can also share some screen recordings. What's the wallet address?

**Comment by polymorpher** [comment]
I sent 1000 ONE as my appreciation for debugging and reporting the issue that the relayer went down, and this issue. It's not a lot given the current market condition, but I hope it is helpful. At this time, there is no bounty program with this project. I am paying out of pocket for this, though perhaps Harmony may be able to reimburse some later

The transaction is
https://explorer.harmony.one/tx/0xdacb1597f41837d70a7190acfab0ad9c15cc168e8741edc87a2f51c78b02add8

**Comment by SystemDisc** [comment]
@polymorpher I'll email you

**Review by urica12 — APPROVED** [review]
code/lib/api/flow.js

**Review by urica12 — APPROVED** [review]
approve

**Review by urica12 — CHANGES_REQUESTED** [review]
looks good i approve this changes

**Review by urica12 — APPROVED** [review]
approve this chang

**Pull request closed without merging**
